AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
   - 'db/**/*'
   - 'config/**/*'
   - 'vendor/**/*'
   - 'script/**/*'
   - 'bin/{rails,rake,bundle}'
   - 'node_modules/**/*'
   - 'lib/tasks/auto_annotate_models.rake'

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/requests/**/*'
